version: "3"
services:
  strada_mysql: # MySQL
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - 3306:3306
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb-use-native-aio=0"
    volumes:
      - "$HOME/mnt/mysql:/var/lib/strada/mysql"
# 추후에 Primary - Secondary 구조로 하게 되면?
#      - "$HOME/mnt/mysql:/var/lib/strada/mysql:ro" #ReadOnly
#      - "$HOME/mnt/mysql:/var/lib/strada/mysql:rw" #ReadWrite
  strada_redis: # Redis
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
  strada_rabbitmq: # RebiitMQ
    image: rabbitmq:3
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_VHOST: azar
    ports:
      - 5672:5672
  strada_application: # strada application, 서버 개발자는 여기 블럭 주석하고 나머지 백엔드 서비스만 띄어놓고, 따로 서버만 개발하면 됨
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on: # 서비스간의 종속성 순서를 조절할 수 있음, 아래 서비스들 다 뜨고 application 띄우기
      - strada_mysql
      - strada_redis
      - strada_rabbitmq
